<?php
/* @var $this Layout */

$this->_response->addHeader('Content-type', 'text/html; charset=utf8');

?>
<!DOCTYPE html>
<html>

<head>
    <title>Тестовый сайт</title>

    <link href="/css/bootstrap.min.css" rel="stylesheet" media="screen" />
    <link href="/css/style.css" rel="stylesheet" media="screen" />
</head>

<body>
<div id="header">
    <div class="logo">Тестовый сайт</div>
</div>

<div id="global-menu">
    <ul>
        <li><a href="/">Главная</a></li>
        <li><a href="/Examples/">Примеры</a></li>
        <li><a href="/Test/">Тестовый контроллер</a></li>
        <li><a href="/Employee/">Сотрудники</a></li>
        <li><a href="/History/">История</a></li>
    </ul>
</div>

<div id="local-menu" class="shadow-frame">
    <?php echo $this->LocalMenu; ?>
</div>

<div id="content" class="shadow-frame">
    <?php echo $this->getContent(); ?>
</div>

<div id="footer">
    Тестовый сайт
</div>

<script src="/js/jquery-3.2.1.min.js" type="text/javascript"></script>
<script src="/js/maskedinput.js" type="text/javascript"></script>
<script src="/js/script.js" type="text/javascript"></script>
</body>
</html>